version: "3.9"

services:
  transformer_torch:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: transformer_torch
    ports:
      - "7860:7860"
    restart: unless-stopped